### ISSUE TITLE
Allow cross-loadings

### ISSUE THREAD

**Issue by pascalvanluit** [M-E-Rademaker/cSEM.DGP#3]
I would like to simulate data with cross-loadings as in the following model:

```r
DGP.model.2 <- " 
    # Structural model
    f1 ~~ rho*f2

    # Measurement model
    f1 =~ lambda*x1 + lambda*x2 + lambda*x3 + delta*x4
    f2 =~ lambda*x4 + lambda*x5 + lambda*x6 "
```
But when I run `generateData()` like so:
```r
DGP.data.2 <- cSEM.DGP::generateData(DGP.model.2, .return_type = "cor",
                                     lambda = c(0.2, 0.5, 0.8),
                                     delta  = c(0.2, 0.5, 0.8),
                                     rho    = c(0.2, 0.5, 0.8),
                                     .handle_negative_definite = "drop"
                                     )
```

I get the following error: `Error: The following error occured in the `parseModel()` function: At least one indicator is connected to several constructs.`

Are you planning on including these cross-loadings soon? That would be really helpful!

**Comment by M-E-Rademaker** [comment]
Hi Pascal,

we created cSEM.DGP as an accompanying package to cSEM. Since cSEM is for composite-based estimators only and (to my knowledge) composite-based estimators such as PLS are unable to deal with items that are attached to several constructs, `generateData()` is not able to simulata data that a composite-based approach cant estimate.

You probably know about the [simulateData()](https://rdrr.io/cran/lavaan/man/simulateData.html) function from lavaan. This should do it. On the downside, it doesnt allow you to create combinations using labels such as in your example above.

**Comment by pascalvanluit** [comment]
Hi Manuel,

Thanks for the quick reply.

Indeed I know about the simulateData() function, and do miss the possibility to create combinations with it.
Will find a way to go about it though.

Cheers
